# Generated by Django 4.0.4 on 2022-05-21 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='timestamp_deadline',
            new_name='timestamp_todo',
        ),
    ]
