# Generated by Django 4.0.4 on 2022-05-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_remove_todotags_todo_todo_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo',
            new_name='tags',
        ),
    ]
